EXPECTED_COLUMNS_AND_ORDER = ['day_ahead_price',
                              'Forecasted_Load', 'Solar_forecast',
                              'Wind_Offshore_forecast',
                              'Wind_Onshore_forecast',
                              'sine_h',
                              'cos_h',
                              'sine_month',
                              'cos_month',
                              'dow',
                              'sine_dow',
                              'cos_dow',
                              'weekend',
                              'lagged_price_24',
                              'solar_sin_inter',
                              'solar_cos_inter',
                              'wind_forecast_total']